import type { FeedItem } from "./feedType";

export const mockFeed: FeedItem[] = [
  {
    id: "p1",
    title: "Conditions parfaites demain matin sur la côte",
    author: "charly",
    sub: "surf",
    score: 312,
    commentsCount: 48,
    createdAt: "2026-01-25T07:10:00Z",
    thumbnail: "https://picsum.photos/seed/surf1/400/250",
    isPinned: true,
  },
  {
    id: "p2",
    title: "Carte interactive des meilleurs spots autour de Bordeaux",
    author: "alice",
    sub: "bordeaux",
    score: 189,
    commentsCount: 22,
    createdAt: "2026-01-24T18:45:00Z",
    url: "https://example.com/spots",
  },
  {
    id: "p3",
    title: "Retour d’expérience : combi 4/3 en plein hiver",
    author: "wavehunter",
    sub: "gear",
    score: 421,
    commentsCount: 64,
    createdAt: "2026-01-24T09:02:00Z",
    thumbnail: "https://picsum.photos/seed/gear1/400/250",
  },
  {
    id: "p4",
    title: "Windy vs Windguru : lequel est le plus fiable ?",
    author: "meteoGeek",
    sub: "meteo",
    score: 97,
    commentsCount: 31,
    createdAt: "2026-01-23T21:30:00Z",
  },
  {
    id: "p5",
    title: "Session solo au lever du jour (photos)",
    author: "saltwater",
    sub: "surf",
    score: 512,
    commentsCount: 89,
    createdAt: "2026-01-23T06:18:00Z",
    thumbnail: "https://picsum.photos/seed/surf2/400/250",
  },
  {
    id: "p6",
    title: "Top 5 des erreurs quand on débute le surf",
    author: "oldtimer",
    sub: "beginner",
    score: 278,
    commentsCount: 41,
    createdAt: "2026-01-22T14:55:00Z",
  },
  {
    id: "p7",
    title: "Analyse houle + vent pour le week-end",
    author: "forecastPro",
    sub: "meteo",
    score: 134,
    commentsCount: 19,
    createdAt: "2026-01-22T09:40:00Z",
  },
  {
    id: "p8",
    title: "Quel volume de planche pour 75kg ?",
    author: "newbie42",
    sub: "gear",
    score: 66,
    commentsCount: 27,
    createdAt: "2026-01-21T20:12:00Z",
  },
];